apiVersion: v1
kind: ConfigMap
metadata:
  name: "beelzebub-configuration"
  namespace: {{ .Values.namespace  }}
  labels:
    {{- include "beelzebub-chart.labels" . | nindent 4 }}
data:
  beelzebub.yaml:
    {{- toYaml .Values.beelzebubCoreConfigs | nindent 12 }}
