apiVersion: v1
kind: Service
metadata:
  name: {{ include "beelzebub-chart.fullname" . }}
  namespace: {{ .Values.namespace  }}
  labels:
    {{- include "beelzebub-chart.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    {{- include "beelzebub-chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}